// --------------------------------------------------------------------------------------------------------------------
// <copyright file="SerializationConfigurationTypes.cs" company="Naos Project">
//    Copyright (c) Naos Project 2019. All rights reserved.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package Naos.Build.Conventions.VisualStudioProjectTemplates.Domain.Test (1.55.47)
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

using Naos.Slack.Serialization.Bson;
using Naos.Slack.Serialization.Json;
using OBeautifulCode.Serialization.Bson;
using OBeautifulCode.Serialization.Json;
using System;
using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;

namespace Naos.Slack.Domain.Test
{
    [ExcludeFromCodeCoverage]
    [GeneratedCode("Naos.Build.Conventions.VisualStudioProjectTemplates.Domain.Test", "1.55.47")]
    public static class SerializationConfigurationTypes
    {
        public static BsonSerializationConfigurationType BsonSerializationConfigurationType => typeof(SlackBsonSerializationConfiguration).ToBsonSerializationConfigurationType();

        public static JsonSerializationConfigurationType JsonSerializationConfigurationType => typeof(SlackJsonSerializationConfiguration).ToJsonSerializationConfigurationType();
    }
}