// --------------------------------------------------------------------------------------------------------------------
// <copyright file="SlackDummyFactory.cs" company="Naos Project">
//    Copyright (c) Naos Project 2019. All rights reserved.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package Naos.Build.Conventions.VisualStudioProjectTemplates.Domain.Test (1.55.47)
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

using FakeItEasy;
using OBeautifulCode.AutoFakeItEasy;
using System;

namespace Naos.Slack.Domain.Test
{
    /// <summary>
    /// A Dummy Factory for types in <see cref="Naos.Slack.Domain"/>.
    /// </summary>
#if !NaosSlackSolution
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [System.CodeDom.Compiler.GeneratedCode("Naos.Slack.Domain.Test", "See package version number")]
    internal
#else
    public
#endif
    class SlackDummyFactory : DefaultSlackDummyFactory
    {
        public SlackDummyFactory()
        {
            /* Add any overriding or custom registrations here. */
        }
    }
}